return {
    "ludovicchabant/vim-gutentags",
    init = function()
        -- =========================================================
        -- PART 1: CAPL LANGUAGE DETECTION CONFIGURATION
        -- =========================================================
        
        -- 1. Map .can and .cin extensions to 'cpp' (C++) filetype
        -- This forces Neovim to treat CAPL files exactly like C++ files
        vim.filetype.add({
            extension = {
                can = 'cpp',
                cin = 'cpp',
            },
        })

--        -- 2. Legacy method: Borrow C++ syntax for a custom 'capl' filetype
--        -- (This is commented out because the method above is simpler and sufficient)
--        -- vim.api.nvim_create_autocmd("FileType", {
--        --     pattern = "capl",
--        --     callback = function()
--        --         vim.opt_local.syntax = "cpp"        -- Use C++ syntax highlighting
--        --         vim.opt_local.commentstring = "// %s" -- Fix comment toggling shortcut
--        --     end,
--        -- })

        -- =========================================================
        -- PART 2: GUTENTAGS (CTAGS) CONFIGURATION
        -- =========================================================

        -- Path to the executable (Use forward slashes / for safety)
        vim.g.gutentags_ctags_executable = 'C:/NgxxFus/ctags-p6.2.20260111.0-x64/ctags.exe'

        -- Load ctags.cnf config file (Contains the custom Regex rules)
        vim.g.gutentags_ctags_extra_args = {
            '--options=C:/NgxxFus/ctags.cnf', 
            '--fields=+niazS',
            '--extras=+q',
        }

        -- Basic project configuration
        vim.g.gutentags_project_root = { '.git' }
        vim.g.gutentags_ctags_tagfile = 'tags'
        
        -- Automatically generate tags on save/new file
        vim.g.gutentags_generate_on_write = 1
        vim.g.gutentags_generate_on_missing = 1
        vim.g.gutentags_generate_on_new = 1
        
        -- Files/folders to ignore (to keep tags clean)
        vim.g.gutentags_ctags_exclude = {
            '*.git', '*.svg', '*.hg',
            'build', 'dist', 'bin',
            'node_modules',
            'cache', 'compiled', 'docs',
            'example', 'bundle', 'vendor',
            '*.md', '*.markdown', '*.txt',
            '*.html', '*.css',
            'doxygen', 'html', -- Ignore folders generated by Doxygen
        }
    end,
}
